# -*- coding: utf-8 -*-
"""Regenerate the README's headline table from the records.

Everything in that table was typed. After the Subject-header correction of
23 September the records changed and the table did not, so the first thing
anyone reading this repository saw was four stale figures: 1,069 threads
instead of 1,103, RoBERTa at 0.359 strict instead of 0.410, 0.545 broad
instead of 0.530, and "48% of what a second annotator achieves" instead of
55%.

The table is now written by this script between two markers, so it cannot
drift again. Run it after any run that changes the records.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import io_paths                                              # noqa: E402

BEGIN = "<!-- headline: generated by scripts/readme_headline.py -->"
END = "<!-- /headline -->"


def load(n):
    return json.load(io.open(io_paths.result_in(n, required=True),
                             encoding="utf-8"))


def main():
    F = load("RESULTS_FINAL.json")
    U = load("RESULTS_UNIFORM.json")
    AG = load("RESULTS_agreement_metrics.json")
    d, a, t = F["dataset"], F["annotation"], F["trivial_floor"]
    la = F["leakage_audit"]
    human = AG["annotator_f1"]["estimate"]

    def best(lab):
        rows = [("RoBERTa", F["transformer_grouped_%s" % lab])]
        rows += [(m, U["%s_uniform_%s" % (m, lab)])
                 for m in ("LinearSVM", "LogReg", "CharNgram")]
        return max(rows, key=lambda r: r[1]["f1"])

    bs, bb = best("strict"), best("broad")
    rows = [
        ("Messages / threads", "%d / %d" % (d["messages"], d["threads"])),
        ("Sensitive, strict (both annotators) / broad (either)",
         "%d (%.1f%%) / %d (%.1f%%)"
         % (d["sensitive_strict"],
            100.0 * d["sensitive_strict"] / d["messages"],
            d["sensitive_broad"],
            100.0 * d["sensitive_broad"] / d["messages"])),
        ("**Cohen's kappa**", "**%.3f** (observed agreement %.3f)"
         % (a["cohens_kappa"], a["observed_agreement"])),
        ("Trivial all-positive floor",
         "F1 %.3f strict, %.3f broad" % (t["strict"], t["broad"])),
        ("**Annotator reference** (second annotator as a classifier)",
         "**F1 %.3f**, MCC %.3f" % (human, a["cohens_kappa"])),
        ("Strongest single term of %s" % format(la["vocabulary_terms"], ","),
         "`'%s'`, F1 %.3f"
         % (la["best_single_term"], la["best_single_term_f1"])),
        ("Best method, strict", "%s F1 %.3f, 95%% CI [%.3f, %.3f]"
         % (bs[0], bs[1]["f1"], bs[1]["f1_ci95"][0], bs[1]["f1_ci95"][1])),
        ("Best method, broad", "%s F1 %.3f, 95%% CI [%.3f, %.3f]"
         % (bb[0], bb[1]["f1"], bb[1]["f1_ci95"][0], bb[1]["f1_ci95"][1])),
    ]

    body = [BEGIN, "", "| | |", "|---|---|"]
    body += ["| %s | %s |" % (k, v) for k, v in rows]
    body += [
        "",
        "Nothing here is near-perfect, every confidence interval overlaps its",
        "neighbours, and that is the result rather than a disappointment. "
        "Quote",
        "every figure against both bounds: the trivial floor below and the "
        "annotator",
        "reference above. The best model reaches %.0f%% of what a second "
        "annotator" % (100.0 * bs[1]["f1"] / human),
        "achieves.",
        "", END,
    ]
    new = "\n".join(body)

    p = os.path.join(REPO, "README.md")
    s = io.open(p, encoding="utf-8").read()
    if BEGIN in s and END in s:
        head = s[:s.index(BEGIN)]
        tail = s[s.index(END) + len(END):]
        s = head + new + tail
    else:
        raise SystemExit("markers not found in README.md; add %s and %s "
                         "around the headline table" % (BEGIN, END))
    io.open(p, "w", encoding="utf-8").write(s)
    print("headline table regenerated from the records:")
    for k, v in rows:
        print("  %-54s %s" % (k.replace("**", ""), v.replace("**", "")))


if __name__ == "__main__":
    main()
